name: makefile

on:
  push:
    branches: [ "trunk" ]
  pull_request:
    branches: [ "trunk" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: make clean all test

  windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: make all
    - uses: actions/upload-artifact@v3.2.1-node20
      with:
        name: windows
        path: lib/simply.exe

  macos:
      runs-on: macos-latest
  
      steps:
      - uses: actions/checkout@v4
      - name: build
        run: make all
      - uses: actions/upload-artifact@v3.2.1-node20
        with:
          name: macos
          path: lib/simply

  linux:
      runs-on: ubuntu-latest
  
      steps:
      - uses: actions/checkout@v4
      - name: build
        run: make all
      - uses: actions/upload-artifact@v3.2.1-node20
        with:
          name: linux
          path: lib/simply
